# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDINFORMATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_WAYTOPAY', models.TextField(choices=[('TCN', 'Tarjeta de Cr\xe9dito Nacional'), ('VS', 'Visa'), ('MC', 'Mastercard'), ('AE', 'American Express'), ('DN', 'Diners'), ('TD', 'Tarjetas D\xe9bito'), ('CB', 'Consignaci\xf3n Bancaria'), ('PB', 'Pagos via Baloto'), ('EF', 'Efecty')], max_length=1)),
                ('TYPE_PRODUCTQUALIFICATION', models.TextField(choices=[('E', 'Excelente'), ('P', 'Promedio'), ('T', 'Terrible')], max_length=1)),
                ('TYPE_SERVICEQUALIFICATION', models.TextField(choices=[('S', 'Satisfecho'), ('N', 'Neutral'), ('I', 'Insatisfecho')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ENTERPRISE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUSSINES_NAME', models.CharField(max_length=50)),
                ('NIT', models.IntegerField()),
                ('PHONE', models.IntegerField()),
                ('EMAIL', models.IntegerField()),
                ('TYPE_CITY_COMPANY', models.TextField(choices=[('BOGOTA', 'Bogot\xe1'), ('MEDELLIN', 'Medellin'), ('BARRANQUILLA', 'Barranquilla'), ('CALI', 'Cali'), ('CARTAGEA_DE_INDIAS', 'Cartagena de indias')], max_length=1)),
                ('ADDRESS', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='addinformation',
            name='client2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.ENTERPRISE'),
        ),
    ]
