# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20171023_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='NIT',
            field=models.CharField(max_length=50),
        ),
    ]
