# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20171027_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinformation',
            name='client2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Enterprise'),
        ),
    ]
