# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_WAYTOPAY', models.TextField(choices=[('TARJETADECREDITONACIONAL', 'Tarjeta de Cr\xe9dito Nacional'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMERICANEXPRESS', 'American Express'), ('DINERS', 'Diners'), ('TARJETASDEBITO', 'Tarjetas D\xe9bito'), ('CONSIGNACIONBANCARIA', 'Consignaci\xf3n Bancaria'), ('PAGOSVIABALOTO', 'Pagos via Baloto'), ('EFECTY', 'Efecty')], max_length=1)),
                ('TYPE_PRODUCTQUALIFICATION', models.TextField(choices=[('5', 'Excelente'), ('3', 'Promedio'), ('1', 'Terrible')], max_length=1)),
                ('TYPE_SERVICEQUALIFICATION', models.TextField(choices=[('5', 'Satisfecho'), ('3', 'Neutral'), ('1', 'Insatisfecho')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('SURNAMES', models.CharField(max_length=80)),
                ('AGE', models.IntegerField()),
                ('TYPE_GENDER', models.TextField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('EMAIL', models.CharField(max_length=80)),
                ('PHONE', models.IntegerField()),
                ('TYPE_CITY', models.TextField(choices=[('1', 'Bogot\xe1'), ('2', 'Medellin'), ('3', 'Barranquilla'), ('4', 'Cali'), ('5', 'Cartagena de indias')], max_length=1)),
                ('SOCIOECONOMIC_LEVEL', models.IntegerField()),
                ('TICKET', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='addinformation',
            name='client1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientt.Client'),
        ),
    ]
