# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTCREATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('SURNAMES', models.CharField(max_length=80)),
                ('EDAD', models.IntegerField()),
                ('TYPE_GENDER', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTROS')], max_length=1)),
            ],
        ),
    ]
