# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGISTERCLIENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('SURNAMES', models.CharField(max_length=80)),
                ('AGE', models.IntegerField()),
                ('TYPE_GENDER', models.TextField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CLIENTCREATE',
        ),
    ]
