# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20171019_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('SURNAMES', models.CharField(max_length=80)),
                ('AGE', models.IntegerField()),
                ('TYPE_GENDER', models.TextField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('EMAIL', models.CharField(max_length=80)),
                ('PHONE', models.IntegerField()),
                ('CITY', models.CharField(max_length=80)),
                ('SOCIOECONOMIC_LEVEL', models.IntegerField()),
                ('TICKET', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='REGISTERCLIENT',
        ),
    ]
