# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20171020_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDINFORMATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_WAYTOPAY', models.TextField(choices=[('TCN', 'Tarjeta de Cr\xe9dito Nacional'), ('VS', 'Visa'), ('MC', 'Mastercard'), ('AE', 'American Express'), ('DN', 'Diners'), ('TD', 'Tarjetas D\xe9bito'), ('CB', 'Consignaci\xf3n Bancaria'), ('PB', 'Pagos via Baloto'), ('EF', 'Efecty')], max_length=1)),
                ('TYPE_PRODUCTQUALIFICATION', models.TextField(choices=[('E', 'Excelente'), ('P', 'Promedio'), ('T', 'Terrible')], max_length=1)),
                ('TYPE_SERVICEQUALIFICATION', models.TextField(choices=[('S', 'Satisfecho'), ('N', 'Neutral'), ('I', 'Insatisfecho')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='CITY',
        ),
        migrations.AddField(
            model_name='client',
            name='TYPE_CITY',
            field=models.TextField(choices=[('1', 'Bogot\xe1'), ('2', 'Medellin'), ('3', 'Barranquilla'), ('4', 'Cali'), ('5', 'Cartagena de indias')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addinformation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.CLIENT'),
        ),
    ]
