# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20171020_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addinformation',
            old_name='client',
            new_name='client1',
        ),
    ]
