# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20171020_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinformation',
            name='TYPE_PRODUCTQUALIFICATION',
            field=models.TextField(choices=[('5', 'Excelente'), ('3', 'Promedio'), ('1', 'Terrible')], max_length=1),
        ),
        migrations.AlterField(
            model_name='addinformation',
            name='TYPE_SERVICEQUALIFICATION',
            field=models.TextField(choices=[('5', 'Satisfecho'), ('3', 'Neutral'), ('1', 'Insatisfecho')], max_length=1),
        ),
        migrations.AlterField(
            model_name='addinformation',
            name='TYPE_WAYTOPAY',
            field=models.TextField(choices=[('TARJETADECREDITONACIONAL', 'Tarjeta de Cr\xe9dito Nacional'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMERICANEXPRESS', 'American Express'), ('DINERS', 'Diners'), ('TARJETASDEBITO', 'Tarjetas D\xe9bito'), ('CONSIGNACIONBANCARIA', 'Consignaci\xf3n Bancaria'), ('PAGOSVIABALOTO', 'Pagos via Baloto'), ('EFECTY', 'Efecty')], max_length=1),
        ),
    ]
