# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20171023_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinformation',
            name='client1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Client'),
        ),
    ]
